apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
<<<<<<< HEAD
        image: akshay53156/ultimate-cicd:replaceImageTag
=======
        image: abhishekf5/ultimate-cicd:12
>>>>>>> fb6b81955f57b6cc3c75e00ac81e6086a365a8ac
        ports:
        - containerPort: 8080
